### ISSUE TITLE
Fix month overflow bug

### ISSUE THREAD

**Issue by bendorshai** [bendorshai/its-a-date#13]
This:
itsadate.parse('2016-09-21');
Parses to Sep 09 2017.
The reason is that it thinks that 09 is the day, and 21 is the month which is 12+9, thus it is jumps to september next year.. :(

Need to implement a validity check fomr month and day, and when one of them is wrong it-a-date must assume that the order is vice-versa.

**Comment by skatz1990** [comment]
But that's what 'day_before_month' is for! The date is parsed as expected if you use the variable wisely... I'm going to implement the validity check but keep in mind that I think it's totally wrong

**Comment by bendorshai** [comment]
there is a setting called "strict" if it's on then its-a-date will not use this agile aproach. so all options are available. 
The functionallity is needed, in the future you can give its a date several dates and it can learn the format by this try&error approach.
